apiVersion: v1
kind: Service
metadata:
  name: hazelcast
spec:
  selector:
    name: hazelcast
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hazelcast
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hazelcast
    spec:
      containers:
      - name: hazelcast
        image: larissaroder/hazelcast:latest
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 10
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "hazelcast-cache"
        imagePullPolicy: Always
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: tz-config
        hostPath:
           path: /usr/share/zoneinfo/America/Sao_Paulo
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
   annotations:
   name: hazelcast
   namespace: default
spec:
   maxReplicas: 1
   minReplicas: 1
   scaleTargetRef:
     apiVersion: apps/v1beta1
     kind: Deployment
     name: hazelcast
   metrics:
   - type: Resource
     resource:
       name: memory
       targetAverageUtilization: 80
